### ISSUE TITLE
Unable to login with AOT and LLVM

### ISSUE THREAD

**Issue by xamarindevelopervietnam** [CrossGeeks/GoogleClientPlugin#29]
Got this error when try to build release with AOT + LLVM + ProGuard + Multidex.
Java.Lang.IncompatibleClassChangeError: no non-static method "Lcom/google/android/gms/auth/api/signin/internal/zzc;.getSignInIntent(Lcom/google/android/gms/common/api/GoogleApiClient;)Landroid/content/Intent;"
  at Java.Interop.JniEnvironment+InstanceMethods.GetMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <a3b39de7d2094d9bb14df621e39d6002>:0 
  at Android.Runtime.JNIEnv.GetMethodID (System.IntPtr kls, System.String name, System.String signature) [0x00007] in <71be6a879ebd48b389b41f39d3d87762>:0 
  at Android.Gms.Auth.Api.SignIn.IGoogleSignInApiInvoker.GetSignInIntent (Android.Gms.Common.Apis.GoogleApiClient client) [0x00012] in <b33f4e69bc6e4921bc84e5573b38a363>:0 
  at Plugin.GoogleClient.GoogleClientManager+<LoginAsync>d__22.MoveNext () [0x0001b] in <b6fce69c42c543f4b06726b36e946653>:0 
--- End of stack trace from previous location where exception was thrown ---
  at connect.me.mobile.Projects.Tdt.IntroPage.IntroV2PageViewModel+<LoginWithGoogleTask>d__25.MoveNext () [0x00093] in <a6c6d773f1a8458bbb0a3f837f5eea10>:0 
  --- End of managed Java.Lang.IncompatibleClassChangeError stack trace ---
java.lang.NoSuchMethodError: no non-static method "Lcom/google/android/gms/auth/api/signin/internal/zzc;.getSignInIntent(Lcom/google/android/gms/common/api/GoogleApiClient;)Landroid/content/Intent;"
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
No issue with out AOT + LLVM

**Comment by maxyhi** [comment]
did you find a solution to this?

**Comment by xamarindevelopervietnam** [comment]
I updated to latest version and it work

**Comment by Pujolsluis** [comment]
I'm glad it's working now @xamarindevelopervietnam , will proceed to close this issue.
