### ISSUE TITLE
Android crash on release mode

### ISSUE THREAD

**Issue by copang** [CrossGeeks/GoogleClientPlugin#48]
**Describe the bug**
I signed in successfully in debug mode, but in release mode my app crashed.
Log:
`Time	Device Name	Type	PID	Tag	Message
03-10 09:21:52.987	Samsung SM-N960F	Info	32639	MonoDroid	java.lang.NoSuchFieldError: no "Lcom/google/android/gms/auth/api/signin/GoogleSignInOptions;" field "DEFAULT_SIGN_IN" in class "Lcom/google/android/gms/auth/api/signin/GoogleSignInOptions;" or its superclasses
	at crc64ee486da937c010f4.ButtonRenderer.n_onClick(Native Method)
	at crc64ee486da937c010f4.ButtonRenderer.onClick(Unknown Source:0)
	at android.view.View.performClick(View.java:7870)
	at android.widget.TextView.performClick(TextView.java:14956)
	at android.view.View.performClickInternal(View.java:7839)
	at android.view.View.access$3600(View.java:886)
	at android.view.View$PerformClick.run(View.java:29363)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7811)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Time	Device Name	Type	PID	Tag	Message
03-10 09:21:52.987	Samsung SM-N960F	Info	32639	MonoDroid	Java.Lang.IncompatibleClassChangeError: no "Lcom/google/android/gms/auth/api/signin/GoogleSignInOptions;" field "DEFAULT_SIGN_IN" in class "Lcom/google/android/gms/auth/api/signin/GoogleSignInOptions;" or its superclasses
  at Java.Interop.JniEnvironment+StaticFields.GetStaticFieldID (Java.Interop.JniObjectReference type, System.String name, System.String signature) <0x795bd9cf70 + 0x0009f> in <2d22f5fc4f5149d79dd7aa129d34883f>:0 
  at Java.Interop.JniType.GetStaticField (System.String name, System.String signature) <0x795bda3490 + 0x0005f> in <2d22f5fc4f5149d79dd7aa129d34883f>:0 
  at Java.Interop.JniPeerMembers+JniStaticFields.GetFieldInfo (System.String encodedMember) <0x795bda0980 + 0x000d3> in <2d22f5fc4f5149d79dd7aa129d34883f>:0 
  at Java.Interop.JniPeerMembers+JniStaticFields.GetObjectValue (System.String encodedMember) <0x795bda0820 + 0x00033> in <2d22f5fc4f5149d79dd7aa129d34883f>:0 
  at Android.Gms.Auth.Api.SignIn.GoogleSignInOptions.get_DefaultSignIn () [0x0000a] in <c191514b138d404abd903df1019299eb>:0 
  at Plugin.GoogleClient.GoogleClientManager..ctor () [0x00018] in <588e30f013034fc98070ae2585b5e296>:0 
  at Plugin.GoogleClient.CrossGoogleClient.CreateGoogleClient () [0x00000] in <588e30f013034fc98070ae2585b5e296>:0 
  at Plugin.GoogleClient.CrossGoogleClient+<>c.<.cctor>b__7_0 () [0x00000] in <588e30f013034fc98070ae2585b5e296>:0 
  at System.Lazy`1[T].PublicationOnlyViaFactory (System.LazyHelper initializer) <0x795d2dba90 + 0x0005b> in <84b67256a3c14618bf29227cc5d9effa>:0 
  at System.Lazy`1[T].CreateValue () <0x795d2dbb90 + 0x000bf> in <84b67256a3c14618bf29227cc5d9effa>:0 
  at System.Lazy`1[T].get_Value () <0x795d2dbd80 + 0x00047> in <84b67256a3c14618bf29227cc5d9effa>:0 
  at Plugin.GoogleClient.CrossGoogleClient.get_Current () [0x00000] in <588e30f013034fc98070ae2585b5e296>:0 
  at AudioBook.ViewModels.LoginViewModel.LoginGoogle () [0x0002f] in <b58d2d0574c047c78f210f1290206742>:0 
  at AudioBook.ViewModels.LoginViewModel.<.ctor>b__25_1 () [0x00062] in <b58d2d0574c047c78f210f1290206742>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <84b67256a3c14618bf29227cc5d9effa>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <ff4ba8b1c5c342bd956b9deb6a813636>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () <0x795bdea8d0 + 0x0004b> in <ff4ba8b1c5c342bd956b9deb6a813636>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <ff4ba8b1c5c342bd956b9deb6a813636>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.87(intptr,intptr)
  --- End of managed Java.Lang.IncompatibleClassChangeError stack trace ---
`

**To Reproduce**
1. Call sign in
2. Crash

**Smartphone (please complete the following information):**
 - Device: Samsung Note 9
 - OS: Android 10
 - Plugin version 1.1.1

**Comment by standamikes** [comment]
+1 same here

**Comment by ilozapad** [comment]
+1 same here

**Comment by Char0394** [comment]
Should be fixed on the latest version

**Comment by Juanoxt890** [comment]
the problem continues
@Char0394 
Works in debug only.

**Comment by rredoh** [comment]
I'm experiencing this issue too

**Comment by copang** [comment]
Here is my solution:
Create file "proguard.cfg" and add in Android project with content:
`
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**
-keep class android.support.v7.widget.** { *; }
-dontwarn android.support.v7.widget.**
-keep class android.support.v7.view.** { *; }
-dontwarn android.support.v7.view.*
`
Remember to set BuildAction to ProguardConfiguration

**Comment by AswinPG** [comment]
I am also getting this error on the latest version

**Comment by AswinPG** [comment]
> Here is my solution:
> Create file "proguard.cfg" and add in Android project with content:
> `-keep class com.google.android.gms.** { *; } -dontwarn com.google.android.gms.** -keep class android.support.v7.widget.** { *; } -dontwarn android.support.v7.widget.** -keep class android.support.v7.view.** { *; } -dontwarn android.support.v7.view.*`
> Remember to set BuildAction to ProguardConfiguration

This Is Working Thanks

**Comment by angelru** [comment]
the same issue
